name: build

on:
  push:
    branches:
      - master

jobs:
  pytest:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
      - name: Run pytest
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/qbot_test
        run: |
          pytest

  lint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install requirements
        run: |
          pip install pre-commit
          pre-commit install
      - name: Run autoflake
        run: |
          pre-commit run autoflake --all-files --show-diff-on-failure
      - name: Run isort
        run: |
          pre-commit run isort --all-files --show-diff-on-failure
      - name: Run black
        run: |
          pre-commit run black --all-files --show-diff-on-failure
